name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Docker Image
      run: docker build -t flask-app:latest .

    - name: Run Tests
      run: docker run --rm flask-app:latest pytest test_app.py

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Tag Image
      run: docker tag flask-app:latest docker.io/sundarjee7771/flask-app:latest

    - name: Push to Docker Hub
      run: docker push docker.io/sundarjee7771/flask-app:latest

